{% set name = "pdfcrop.pl" %}
{% set version = "1.42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ho-tex/pdfcrop/archive/v{{ version }}.tar.gz
  sha256: 8f29a3f6b77a56e9fd973bcb9ec7cb5d2411ea4b9f8936174c3b371b4601f2e1

build:
  number: 0
  noarch: generic
  script:
    - cp {{ name }} $PREFIX/bin/

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl
    - ghostscript

test:
  commands:
    - {{ name }} --version 2>&1 | grep {{ version }}

about:
  home: https://github.com/ho-tex/pdfcrop
  license: LPPL-1.3c
  license_family: OTHER
  license_file: LICENCE
  summary: Calculates the BoundingBox for each page using ghostscript and removes margins.

extra:
  recipe-maintainers:
    - tdegeus
