{% set name = "pdfcrop.pl" %}
{% set version = "1.41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ho-tex/pdfcrop/archive/v{{ version }}.tar.gz
  sha256: a61e3610f1386413127613c70cd6c1d28adf34e36cfa50082f0dcffb2059b823

build:
  number: 0
  noarch: generic
  script:
    - cp {{ name }} $PREFIX/bin/

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl
    - ghostscript

test:
  commands:
    - {{ name }} --version 2>&1 | grep {{ version }}

about:
  home: https://github.com/ho-tex/pdfcrop
  license: LPPL-1.3c
  license_family: OTHER
  license_file: LICENCE
  summary: Calculates the BoundingBox for each page using ghostscript and removes margins.

extra:
  recipe-maintainers:
    - tdegeus
